Update course-manager-schema-setup.roo
Having a field "tag" in an entity "Tag" causes a generation of an input field with id
"c_org_rooinaction_coursemanager_model_Tag_tag" in the create.jspx page.

<form:create id="fc_org_rooinaction_coursemanager_model_Tag" modelAttribute="tag" path="/tags" render="${empty dependencies}" z="5lywplbe5H/qB3L4d4NDJavhl9I=">
...
<field:input field="name" id="c_org_rooinaction_coursemanager_model_Tag_tag" max="25" min="1" required="true" z="mzy1IkMjLBzazsVeN3p4T8bcfQ4="/>
...
    </form:create>


This in turn causes:
TRACE org.springframework.beans.TypeConverterDelegate - Field [<any tag name here>] isn't an enum value
java.lang.NoSuchFieldException: <any tag name here>
	at java.lang.Class.getField(Class.java:1522)
	at org.springframework.beans.TypeConverterDelegate.attemptToConvertStringToEnum(TypeConverterDelegate.java:316)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:243)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:93)